import type { MetadataRoute } from "next";

/**
 * /robots.txt — auto-generated by Next.js App Router.
 *
 * Allow all crawlers; sitemap link helps Google/Bing index instantly.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: { userAgent: "*", allow: "/" },
    sitemap: "https://labs.cuvetsmo.com/sitemap.xml",
    host: "https://labs.cuvetsmo.com",
  };
}
