import type { MetadataRoute } from "next";

/**
 * /sitemap.xml — auto-generated by Next.js App Router.
 *
 * Labs index is a single-page site; we list the root plus the lab outbound
 * URLs as hints to crawlers (Google may not follow them since they're on
 * different hosts, but it documents the discovery surface).
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const base = "https://labs.cuvetsmo.com";
  const now = new Date();

  return [
    { url: `${base}/`, lastModified: now, changeFrequency: "weekly", priority: 1 },
  ];
}
